 theme: jekyll-theme-midnight
title: "Electrical Cars"
description: "A website that puts together the specs and looks of various Top Electrical Vehicals"
gitorg: "https://github.com/Firestorm0986/frontend-proj"
description: "January 3 2023"
google_analytics:
